### ISSUE TITLE
ReCaptcha funktioniert nicht, keine Neuregistrierung möglich

### ISSUE THREAD

**Issue by anhaefr01** [mittwald/shopware-security-tools#27]
Shopware v5.6.2, Mittwald Security Tools v 1.6.0 - Recaptcha v2/v3. 
Neuregistrierung im Shop nach installation des Tools nicht mehr möglich. Der Vorgang wird mit einer Recaptcha Fehlermeldung abgebrochen.

Vor dem Mittwald Plugin war "reCAPTCHA v3 für Shopware" v. Mediagraphik GmbH installiert.

**Comment by pstranghoener** [comment]
Hallo, 

wir bieten über Github keinen Support an. 
Bitte eröffnen Sie  ein Ticket über den Shopware Account unter account.shopware.com 

Viele Grüße
