### ISSUE TITLE
recaptcha__de.js wird mehrfach geladen

### ISSUE THREAD

**Issue by Prime-Host** [mittwald/shopware-security-tools#28]
Hallo,

die Datei recaptcha__de.js wird mehrfach geladen. Ein anderes Modul das recaptcha verwendet ist nicht installiert.
Sobald das Mittwald Modul deaktiviert ist wird keine Datei von "www.gstatic.com" geladen.

![Bildschirmfoto von 2021-01-15 11-57-19](https://user-images.githubusercontent.com/16927261/104716978-f1162200-5728-11eb-9ccb-f07918750526.png)

Freundliche Grüße
Kevin Nordloh

**Comment by patrickhilker** [comment]
Hey Kevin, danke für den Hinweis! Wir schauen uns das an.

- Patrick

**Comment by pstranghoener** [comment]
Dieses Verhalten ist ganz normaler Standard von Google. Wir haben darauf keinen Einfluss, selbst auf der Demo Seite von ReCaptcha ist dieses so: https://www.google.com/recaptcha/api2/demo
