### ISSUE TITLE
Fehlermeldung bei Login 

### ISSUE THREAD

**Issue by tuami** [mittwald/shopware-security-tools#6]
Shopware 5.2.12

Hi!
Klickt ein Benutzer ohne seine Logindaten anzugeben im Loginbereich auf "Anmelden"
erscheint eine Fehlermeldung.
1. 
![grafik](https://cloud.githubusercontent.com/assets/25531312/22595451/cfb02538-ea27-11e6-8210-158abdd389c2.png)
2. 
![grafik](https://cloud.githubusercontent.com/assets/25531312/22595463/dcedc8c2-ea27-11e6-8a0c-38bf9605b926.png)

Deaktiviert man die Security Tools erscheint die normale Shopware Fehlermeldung.

![grafik](https://cloud.githubusercontent.com/assets/25531312/22595511/0ee1ea84-ea28-11e6-8dae-7db711fb0a23.png)

**Comment by pstranghoener** [comment]
Hallo,

vielen Dank für die Bugmeldung, dieser Bug ist uns bereits bekannt und wird in der nächsten Version gefixt. 

Viele Grüße Philipp
vom Mittwald Shopware Team
