### ISSUE TITLE
V  1.3.0 Kunden können sich nicht mehr anmelden.

### ISSUE THREAD

**Issue by tuami** [mittwald/shopware-security-tools#9]
Hallo, nach Update auf die V 1.3.0 haben wir diverse Kundenmeldungen erhalten, dass sie kein Kundenkonto mehr anlegen können. Wir haben das Plugin solange deaktiviert, können gerne auch eine Testumgebung einrichten mit aktiver letzten Version.

"Ich versuche, ein Kundenkonto anzulegen, das klappt leider nicht, Eingabe wird ständig neu verlangt "

Shopware 5.2.20

Danke 

tuami

**Comment by philippmahlow** [comment]
Hi,
das Problem ist uns bisher nicht bekannt. Ich konnte das hier jetzt auf die Schnelle auch nicht nachstellen - kannst du mir einmal einen Screenshot von eurer Pluginkonfiguration bereitstellen?

Wenn es kein großer Aufwand ist, wäre eine Testumgebung, in der der Fehler auftritt natürlich noch besser.

Viele Grüße
Philipp

**Comment by tuami** [comment]
Ich richte eben mal die Testumgebung ein. Melde mich gleich nochmal. Danke

**Comment by philippmahlow** [comment]
Zugangsdaten kannst du mir dann per E-Mail an p.mahlow@mittwald.de schicken.

Danke

**Comment by philippmahlow** [comment]
Ich hab bisher noch nichts bekommen - hängt da etwas bei mir im Spamfilter? Oder läuft es jetzt schon?

Viele Grüße
Philipp

**Comment by pstranghoener** [comment]
Ich denke das hat sich erledigt ist über ein 1 Jahr her.
